# Generated by Django 3.2.19 on 2023-05-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_humanitaspost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humanitaspost',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
