# Generated by Django 3.2.19 on 2023-05-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_humanitaspost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humanitaspost',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
