# Generated by Django 3.2.19 on 2023-05-13 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('timeblock', models.CharField(choices=[('A', '10:00-11:00'), ('B', '11:00-12:00'), ('C', '12:00-13:00'), ('D', '13:00-14:00'), ('E', '14:00-15:00'), ('F', '15:00-16:00')], default='A', max_length=10)),
                ('helptype', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
