# Generated by Django 3.2.19 on 2023-05-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='timeblock',
            field=models.CharField(choices=[('A', '10:00-10:20'), ('B', '10:30-10:50'), ('C', '11:00-11:20'), ('D', '11:30-11:50'), ('E', '12:00-12:20'), ('F', '15:00-15:20'), ('G', '15:30-15:50')], default='A', max_length=10),
        ),
    ]
