# Generated by Django 3.2.19 on 2023-05-18 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_timeblock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='name',
        ),
    ]
