# Generated by Django 3.2.19 on 2023-05-18 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_rename_user_booking_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='user',
        ),
    ]
