# Generated by Django 3.2.19 on 2023-05-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_rename_name_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='timeblock',
            field=models.CharField(choices=[('10:00', '10:00-10:20'), ('10:30', '10:30-10:50'), ('11:00', '11:00-11:20'), ('11:30', '11:30-11:50'), ('12:00', '12:00-12:20'), ('15:00', '15:00-15:20'), ('15:30', '15:30-15:50')], default='10:00', max_length=10),
        ),
    ]
