# Generated by Django 3.2.19 on 2023-05-10 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_humanitaspost_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humanitaspost',
            name='status',
        ),
    ]
