# Generated by Django 3.2.19 on 2023-05-10 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20230510_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humanitaspost',
            name='slug',
        ),
    ]
